config/routes.rb
ClickYCome::Application.routes.draw do

  resources :types

  resources :orders

  resources :offices

  resources :users

  resources :menu_dishes

  resources :menus

  resources :dishes
  
  root :to => 'pages#index'
  
  match '/signin', :to => 'facebook#new'
  match '/facebook/callback', :to => 'facebook#callback'
  match '/signout', :to => 'facebook#destroy'

end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :address, :city, :geo, :name, :references, :state, :zip
  has_many :users
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/new
  # GET /offices/new.json
  def new
    @office = Office.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(params[:office])

    respond_to do |format|
      if @office.save
        
        # Associating office to user
        user = current_user
        user.office_id = @office.id
        user.cel_phone = params[:user][:cel_phone] if params[:user]
        user.save
        
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render json: @office, status: :created, location: @office }
      else
        format.html { render action: "new" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.json
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to offices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if current_user.cel_phone.nil? %>
  <%= fields_for current_user do |uf| %>
  <div class="field">
	Teléfono móvil:<br />
	<%= uf.text_field :cel_phone %>
  </div>
  <% end %>
  <% end %>

  <div class="field">
    Nombre de la Empresa:<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    Dirección:<br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    Ciudad:<br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    Estado:<br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    Código Postal:<br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    Referencias para llegar a la oficina:<br />
    <%= f.text_area :references %>
  </div>
  <div class="field">
    <%= f.hidden_field :geo %>
  </div>
  <div class="actions">
    <input type="submit" name="commit" value="Enviar registro" >
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render 'form' %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<h1>Listing offices</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>References</th>
    <th>Geo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offices.each do |office| %>
  <tr>
    <td><%= office.name %></td>
    <td><%= office.address %></td>
    <td><%= office.city %></td>
    <td><%= office.state %></td>
    <td><%= office.zip %></td>
    <td><%= office.references %></td>
    <td><%= office.geo %></td>
    <td><%= link_to 'Show', office %></td>
    <td><%= link_to 'Edit', edit_office_path(office) %></td>
    <td><%= link_to 'Destroy', office, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New office</h1>

<%= render 'form' %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @office.name %>
</p>

<p>
  <b>Address:</b>
  <%= @office.address %>
</p>

<p>
  <b>City:</b>
  <%= @office.city %>
</p>

<p>
  <b>State:</b>
  <%= @office.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @office.zip %>
</p>

<p>
  <b>References:</b>
  <%= @office.references %>
</p>

<p>
  <b>Geo:</b>
  <%= @office.geo %>
</p>


<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>