config/routes.rb
ClickYCome::Application.routes.draw do

  resources :types

  resources :orders

  resources :offices

  resources :users

  resources :menu_dishes

  resources :menus

  resources :dishes
  
  root :to => 'pages#index'
  
  match '/signin', :to => 'facebook#new'
  match '/facebook/callback', :to => 'facebook#callback'
  match '/signout', :to => 'facebook#destroy'

end

app/models/menu_dish.rb
class MenuDish < ActiveRecord::Base
  attr_accessible :dish_id, :menu_id
  belongs_to :menu
  belongs_to :dish
end

app/controllers/menu_dishes_controller.rb
class MenuDishesController < ApplicationController
  # GET /menu_dishes
  # GET /menu_dishes.json
  def index
    @menu_dishes = MenuDish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menu_dishes }
    end
  end

  # GET /menu_dishes/1
  # GET /menu_dishes/1.json
  def show
    @menu_dish = MenuDish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu_dish }
    end
  end

  # GET /menu_dishes/new
  # GET /menu_dishes/new.json
  def new
    @menu_dish = MenuDish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu_dish }
    end
  end

  # GET /menu_dishes/1/edit
  def edit
    @menu_dish = MenuDish.find(params[:id])
  end

  # POST /menu_dishes
  # POST /menu_dishes.json
  def create
    @menu_dish = MenuDish.new(params[:menu_dish])

    respond_to do |format|
      if @menu_dish.save
        format.html { redirect_to @menu_dish, notice: 'Menu dish was successfully created.' }
        format.json { render json: @menu_dish, status: :created, location: @menu_dish }
      else
        format.html { render action: "new" }
        format.json { render json: @menu_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menu_dishes/1
  # PUT /menu_dishes/1.json
  def update
    @menu_dish = MenuDish.find(params[:id])

    respond_to do |format|
      if @menu_dish.update_attributes(params[:menu_dish])
        format.html { redirect_to @menu_dish, notice: 'Menu dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_dishes/1
  # DELETE /menu_dishes/1.json
  def destroy
    @menu_dish = MenuDish.find(params[:id])
    @menu_dish.destroy

    respond_to do |format|
      format.html { redirect_to menu_dishes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/menu_dishes_helper.rb
module MenuDishesHelper
end

app/views/menu_dishes/_form.html.erb
<%= form_for(@menu_dish) do |f| %>
  <% if @menu_dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_dish.errors.count, "error") %> prohibited this menu_dish from being saved:</h2>

      <ul>
      <% @menu_dish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :menu_id %><br />
    <%= f.text_field :menu_id %>
  </div>
  <div class="field">
    <%= f.label :dish_id %><br />
    <%= f.text_field :dish_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_dishes/edit.html.erb
<h1>Editing menu_dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_dish %> |
<%= link_to 'Back', menu_dishes_path %>

app/views/menu_dishes/index.html.erb
<h1>Listing menu_dishes</h1>

<table>
  <tr>
    <th>Menu</th>
    <th>Dish</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menu_dishes.each do |menu_dish| %>
  <tr>
    <td><%= menu_dish.menu_id %></td>
    <td><%= menu_dish.dish_id %></td>
    <td><%= link_to 'Show', menu_dish %></td>
    <td><%= link_to 'Edit', edit_menu_dish_path(menu_dish) %></td>
    <td><%= link_to 'Destroy', menu_dish, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu dish', new_menu_dish_path %>

app/views/menu_dishes/new.html.erb
<h1>New menu_dish</h1>

<%= render 'form' %>

<%= link_to 'Back', menu_dishes_path %>

app/views/menu_dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Menu:</b>
  <%= @menu_dish.menu_id %>
</p>

<p>
  <b>Dish:</b>
  <%= @menu_dish.dish_id %>
</p>


<%= link_to 'Edit', edit_menu_dish_path(@menu_dish) %> |
<%= link_to 'Back', menu_dishes_path %>